package by.epamtc.zarutski.controller.command;

public enum ParameterName {

    REGISTRATION, AUTHENTICATION, LOGOUT, LOCALIZATION,
    GO_TO_MAIN_PAGE, GO_TO_AUTHENTICATION_PAGE, GO_TO_PERSONAL_AREA, GO_TO_REGISTRATION_PAGE,
    GO_TO_CARDS, GO_TO_ACCOUNTS, GO_TO_PAYMENTS, GO_TO_SEARCH_USER

}